import { z } from 'zod'
import { type Item } from '@/types/data'

export const init = () => {
  z.config({
    customError: (iss) => {
      if (!iss.input) return 'is missing'

      const map = {
        too_big: `is too large (max: ${iss.maximum})`,
        too_small: `is too small (min: ${iss.minimum})`,
      }

      return map[iss.code as keyof typeof map] || 'is invalid'
    },
  })
}

const error = <P>(error: string, params?: P) => ({
  error,
  ...(typeof params === 'string' ? { error: params } : params),
})

const text = (params?: Parameters<z._ZodString['nonempty']>[0]) =>
  z.string().nonempty(params)

const date = (params?: Parameters<typeof z.coerce.date>[0]) =>
  z.coerce.date<Date>(params)

const past = <P extends Parameters<typeof z.refine>[1]>(d?: Date, params?: P) =>
  Object.assign(date(params), {
    _refine: <T extends Record<string, Date>>(k: keyof T, params?: P) => [
      (data: T) => data[k] < (d || data.createdAt || new Date()),
      error('is not in the past', params),
    ],
  })

const future = <P extends Parameters<typeof z.refine>[1]>(
  d?: Date,
  params?: P
) =>
  Object.assign(date(params), {
    _refine: <T extends Record<string, Date>>(k: keyof T, params?: P) => [
      (data: T) => data[k] > (d || data.createdAt || new Date()),
      error('is not in the future', params),
    ],
  })

const _enum = <T extends Item[]>(
  arr: T,
  params?: Parameters<typeof z.enum>[1]
) =>
  z.enum(
    arr.map((_) => _.value) as T[number]['value'][],
    error(`is not one of: ${arr.map((_) => _.label).join(', ')}.`, params)
  )

const auto = ['id', 'ids', 'createdAt', 'updatedAt', 'deletedAt'] as const
const dates = { createdAt: date(), updatedAt: date() }
const deletedAt = date().nullish()

type AutoGenerated = (typeof auto)[number]
type PrimaryKey = 'int' | 'xid' | 'cuid' | 'guid' | 'ulid' | 'uuid' | 'nanoid'
type TableShape = z.core.$ZodLooseShape & { [K in AutoGenerated]?: never }

export const omit = <S extends z.core.$ZodLooseShape>(shape: z.ZodObject<S>) =>
  shape.omit(
    Object.fromEntries(
      auto.filter((k) => shape.shape[k]).map((k) => [k, !!shape.shape[k]])
    ) as { [K in AutoGenerated]?: true }
  )

const table = <
  S extends TableShape,
  P extends PrimaryKey = 'int',
  T extends boolean = true,
  D extends boolean = false,
>(
  shape: S,
  table?: { primaryKey?: P; timestamps?: T; softDelete?: D },
  params?: Parameters<typeof z.object>[1]
) => {
  const { primaryKey = 'int', timestamps = true, softDelete } = table ?? {}

  let schema = z.object(
    {
      id: z[primaryKey](),
      ...shape,
      ...((timestamps ?? true) ? dates : {}),
      ...(softDelete ? { deletedAt } : {}),
    },
    params
  ) as z.ZodObject<
    { id: ReturnType<(typeof z)[P]> } & S &
      (T extends true ? typeof dates : unknown) &
      (D extends true ? { deletedAt: typeof deletedAt } : unknown)
  >

  Object.entries(z.object(shape).shape).forEach(([k, v]) => {
    if ('_refine' in v) {
      const _refine = v._refine as (
        k: keyof S,
        params?: Parameters<typeof z.refine>[1]
      ) => Parameters<typeof z.refine>

      schema = schema.refine(..._refine(k, { path: [k] }))
    }
  })

  return schema
}

export const db = {
  text,
  date: Object.assign(date, { past, future }),
  enum: _enum,
  table,
}

export const form = <S extends z.core.$ZodLooseShape>(shape: z.ZodObject<S>) =>
  omit(shape).extend(
    Object.fromEntries(
      Object.entries(shape.shape)
        .filter(([, v]) => v instanceof z.ZodEnum)
        .map(([k]) => [k, text()])
    ) as Record<
      { [K in keyof S]: S[K] extends z.ZodEnum ? K : never }[keyof S],
      z.ZodString
    >
  )

export const bulk = <
  S extends z.core.$ZodLooseShape & { id: P; ids?: never },
  P extends ReturnType<(typeof z)[PrimaryKey]>,
>(
  shape: z.ZodObject<S>
) => ({
  create: omit(shape).array().nonempty(),
  get update() {
    return z.object({
      ids: shape.shape.id.array().nonempty() as z.ZodArray<
        typeof shape.shape extends { id: infer U } ? U : never
      >,
      ...this.create.unwrap().partial().shape,
    })
  },
  get delete() {
    return this.update.shape.ids
  },
})

export * from 'zod'
